---
- name: Uninstall WAC
  win_package:
    path: "{{ wac_local_install_path }}"
    product_id: "{{ wac_product_id }}"
    state: absent
  register: wac_uninstall

- name: Restart Server
  win_reboot:
    msg: Rebooting to Complete Windows Admin Center Installation
  when: wac_uninstall.reboot_required

- name:
  import_tasks: delegation.yml
  vars:
    wac_server_hostname: "$null"
