---
dependency:
  name: galaxy
driver:
  name: delegated
  hostname: zollo-vca01.home.zollo.net
  username: svc.ansible@vsphere.local
  password: ekiYOKR4!5t@2GBC
  validate_certs: false
  datacenter: Homelab
  folder: /CI Infrastructure/Instances/
  vm_username: Administrator
  vm_password: password123!
  connection: ssh
  port: 22
  shell_type: powershell
  become_method: runas
  become_user: Administrator
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "c1-${GIT_COMMIT}"
    template: win2019-core
    snapshot_src: base
    cluster: Zollo Cluster
    memory_mb: 4096
    cpus: 2
    datastore: lun4-nvme
    network:
      - name: 192.168.40.0-vlan40-dmz
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  ansible_args:
    - -vvvv
  playbooks:
    create: ../../drivers/vsphere_ssh/create.yml
    converge: playbook.yml
    destroy: ../../drivers/vsphere_ssh/destroy.yml
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
